// <auto-generated />
using System;
using FallDetectionMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FallDetectionMonitor.Migrations
{
    [DbContext(typeof(FallDetectionDbContext))]
    [Migration("20260617161247_AddMlTelemetryToSensorReadings")]
    partial class AddMlTelemetryToSensorReadings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FallDetectionMonitor.Models.AlertEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EmergencyServicesCalledAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextOfKinCalledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResolutionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WearableDeviceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WearableDeviceId");

                    b.ToTable("AlertEvents");
                });

            modelBuilder.Entity("FallDetectionMonitor.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasNextOfKin")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("FallDetectionMonitor.Models.SensorReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AccelX")
                        .HasColumnType("float");

                    b.Property<double>("AccelY")
                        .HasColumnType("float");

                    b.Property<double>("AccelZ")
                        .HasColumnType("float");

                    b.Property<double>("AltitudeM")
                        .HasColumnType("float");

                    b.Property<bool>("BuzzerActive")
                        .HasColumnType("bit");

                    b.Property<bool>("FallDetected")
                        .HasColumnType("bit");

                    b.Property<double>("GyroX")
                        .HasColumnType("float");

                    b.Property<double>("GyroY")
                        .HasColumnType("float");

                    b.Property<double>("GyroZ")
                        .HasColumnType("float");

                    b.Property<int>("HeartRateBpm")
                        .HasColumnType("int");

                    b.Property<bool>("LedActive")
                        .HasColumnType("bit");

                    b.Property<double>("MlFallScore")
                        .HasColumnType("float");

                    b.Property<bool>("MlTriggered")
                        .HasColumnType("bit");

                    b.Property<double>("PressureHpa")
                        .HasColumnType("float");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WearableDeviceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WearableDeviceId");

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("FallDetectionMonitor.Models.WearableDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("WearableDevices");
                });

            modelBuilder.Entity("FallDetectionMonitor.Models.AlertEvent", b =>
                {
                    b.HasOne("FallDetectionMonitor.Models.WearableDevice", "WearableDevice")
                        .WithMany("AlertEvents")
                        .HasForeignKey("WearableDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WearableDevice");
                });

            modelBuilder.Entity("FallDetectionMonitor.Models.SensorReading", b =>
                {
                    b.HasOne("FallDetectionMonitor.Models.WearableDevice", "WearableDevice")
                        .WithMany("SensorReadings")
                        .HasForeignKey("WearableDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WearableDevice");
                });

            modelBuilder.Entity("FallDetectionMonitor.Models.WearableDevice", b =>
                {
                    b.HasOne("FallDetectionMonitor.Models.Patient", "Patient")
                        .WithMany("WearableDevices")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("FallDetectionMonitor.Models.Patient", b =>
                {
                    b.Navigation("WearableDevices");
                });

            modelBuilder.Entity("FallDetectionMonitor.Models.WearableDevice", b =>
                {
                    b.Navigation("AlertEvents");

                    b.Navigation("SensorReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
